### ISSUE TITLE
deepctr.py 中 user_feat 和 item_feat 的创建问题

### ISSUE THREAD

**Issue by miandai** [RManLuo/MAMDR#2]
文件 model_zoo/DeepCTR/deepctr.py 第 115 行：

`emb_layer = SparseFeat(input_name, self.n_uid, self.model_config['user_dim'], embedding_name=emb_name)`

是否应为：

`emb_layer = SparseFeat(input_name, n, dim, embedding_name=emb_name)`

因为调用 build_emb 函数的，不仅有 user_feat，还有 item_feat，这里全设为 n_uid、user_dim 不合理。

model_zoo/DeepMTLCTR/deep_mtl_ctr.py 的第 120 行也是同样问题。

**Comment by RManLuo** [comment]
感谢指出，已在 f6dc5b799150103e8f270f329217bf541c44a67d 中修复。此处代码只有在Amazon数据集中，需要训练用户和物品embedding时才会使用。由于用户数量比物品数量多，因此，此问题只会造成额外的显存开销，并不会对最终实验结果造成影响。
