### ISSUE TITLE
Star 模型 Auxiliary Network 的输入是否只需 domain_emb？

### ISSUE THREAD

**Issue by miandai** [RManLuo/MAMDR#3]
从代码 auxiliary_net.py 来看，Star 模型 Auxiliary Network 的输入，除了有 domain_emb，还有 user_emb、item_emb。

原论文《One Model to Serve All...》中关于 Auxiliary Network 的描述「The domain indicator is first mapped into embedding vector and concatenated with other features. The auxiliary network then computes forward pass with respect to the concatenated features to gets the one-dimensional output」，也是输入所有特征。

我理解这里应该只包含 domain_emb 才对，不该有其它特征，这样辅助网络才能学习到 domain indicator 的独有信息。不知 Raymond 是否跟我有同样困惑。

**Comment by RManLuo** [comment]
这里的描述是The auxiliary network then computes forward pass with respect to the **concatenated features** to gets the one-dimensional output。我认为 concatenated features指的就是三个特征的拼接。

**Comment by miandai** [comment]
> 这里的描述是The auxiliary network then computes forward pass with respect to the **concatenated features** to gets the one-dimensional output。我认为 concatenated features指的就是三个特征的拼接。

对，您这里的实现跟论文是一致的，没有问题。内网里一作的分享也是所有特征，不过二作的 ATA 里是说只有场景特征，跟我理解一致。多谢解答。我直接钉钉问一作吧～
