### ISSUE TITLE
数学公式

### ISSUE THREAD

**Issue by pengpengtao** [RManLuo/MAMDR#5]
作者，您好，MDR的目标函数是否需要加一个中括号吗，没有太明白，根据论文描述，应该是有一个中括号
![图片1](https://github.com/RManLuo/MAMDR/assets/63086628/d375b8cd-f816-4dd7-a850-ec84d83ee86e)

**Comment by RManLuo** [comment]
您好，您的理解是对的，为了公式简洁，我们省略了中括号。

**Comment by pengpengtao** [comment]
作者，您好，AUC评估标准我了解，RANK的评估指标是什么意思，希望您能帮我解惑，非常感谢
